input: `i$0:`input1
/ input:199 200 208 210 200 207 240 269 260 263
1692~-1+/>':input
/ 1724~-1+/>':2_+/(;:':;:'::':)@\:input  / original. would prefer n-scan here
1724~+/</-3 3_\:input  / after reading reddit

input:+" "\'0:`input2
/ input:+" "\'";"\"forward 5;down 5;forward 8;up 3;down 8;forward 2"
num:`i$ :/input
dir:"fdu"?*'*input
1990000~*/+/num*coord:(1 0;0 1;0 -1)dir
fwd:+\f:num**+coord
depth:+\f*+\num* :/+coord
1975421260~*/ :/'(depth;fwd)

\\
